# fly.toml app configuration file generated for twbbcodebot on 2024-12-23T15:53:42Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "twbbcodebot"
primary_region = "mad"

[build]

[processes]
app = "python main.py"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[services]
  internal_port = 8080
  [[services.ports]]
    port = "8080"
  [[services.tcp_checks]]
    grace_period = "30s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

[[vm]]
  size = "shared-cpu-1x"
